cargo-features = ["strip"]

[package]
name = "wordfind"
version = "0.1.0"
authors = ["Niklas Elsbrock <niklas@els-web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[dependencies]
rustyline = "7.1.0"
